### Write in your own words how does the EIG command work on pseudocode level (enough to explain the mathematics behind it). Also write out the main formulae in Jupyter Notebook.   

In [1]:
import numpy as np
import numpy.linalg as la

In [6]:
eigen_value,eigen_vector=la.eig(np.array([[2,4],[4,8]]))

The eigen value and eigen vector of square matrix A can be computed using the property 
\begin{align}
AV=\lambda V \\
AV-\lambda V =0 \\
(A-\lambda I) V=0 \\
| A -\lambda I| =0
\end{align}

where 𝜆 is eigen values and V is eigen vector and I is the identity matrix






### Show mathematically how the vector form of Covariance Matrix representation can be deduced from the matrix form (you can choose your own denotation for eigenvectors) 

let $u$=$v$=$[\vec{u_1},\vec{u_2}, ...,\vec{u_d}]$ then <br/>
$\sum =[ \vec{u_1},\vec{u_2}, ...,\vec{u_d}]
\begin{bmatrix} \lambda_i & 0 & 0 \\ 0 & \lambda_j & 0 \\ 0 & 0 & \lambda_d\end{bmatrix}[ \vec{u_1},\vec{u_2}, ..., \vec{u_d}]^T$ <br/>
$=[ \vec{u_1},\vec{u_2}, ...,\vec{u_d}].\begin{bmatrix} \lambda_1 u_1 \\ \lambda_2 u_2  \\ \vdots  \\  \lambda_d u_d\end{bmatrix}$ <br/>
$ = \lambda_1 u_1 u_1^T + \lambda_2 u_2 u_2^T+ \lambda_2 u_2 u_2^T+ .... +\lambda_d u_d u_d^T$ <br/>
$=\lambda_i u_i u_i^T  $
$  = \sum \limits _{i=1} ^{D}\lambda_i u_i u_i^T$

### Replicate all the steps of https://sebastianraschka.com/Articles/2014_pca_step_by_step.html up to the end of point 5. You don't need to do point 3)a because our focus is on the Covariance matrix. 

In [10]:
mu_vec1 = np.array([0,0,0])
cov_mat1 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class1_sample = np.random.multivariate_normal(mu_vec1, cov_mat1, 20).T

In [11]:
class1_sample 

array([[ 2.09209836, -0.4651235 ,  0.85574773, -0.28712455,  0.40861041,
         1.25377641, -1.19361492, -0.917519  , -1.4855994 ,  0.26912106,
         0.56169498,  1.45660556, -1.03373062,  0.18244582,  0.61258553,
         0.58588449,  1.79541933, -1.16276156,  1.33654629,  0.85752825],
       [-0.70323619, -2.25791333,  0.41918399, -0.21786285, -0.17761223,
         0.10540902,  1.89943131, -0.98874114,  0.70645644,  0.53073032,
        -0.94154117,  0.4068117 , -1.22378777, -2.2072193 , -0.32235005,
         0.52478673,  0.77001893,  0.39641611,  0.86301552,  0.17014234],
       [ 0.36171216,  0.48398001, -0.79080765, -0.03720496, -0.04348462,
         1.12579904, -0.3419861 , -0.32501283, -0.19969117, -1.40855794,
        -1.45416524,  0.32853861, -1.77407724, -0.86042784,  0.83700655,
         0.97242816,  0.46933776,  0.17569047,  0.72930022, -2.05781973]])

In [16]:
assert class1_sample.shape == (3,20), "The matrix has not the dimensions 3x20"
class1_sample.shape

(3, 20)

In [17]:
mu_vec2 = np.array([1,1,1])
cov_mat2 = np.array([[1,0,0],[0,1,0],[0,0,1]])
class2_sample = np.random.multivariate_normal(mu_vec2, cov_mat2, 20).T
assert class2_sample.shape == (3,20), "The matrix has not the dimensions 3x20"

In [18]:
all_samples = np.concatenate((class1_sample, class2_sample), axis=1)
assert all_samples.shape == (3,40), "The matrix has not the dimensions 3x40"

In [19]:
mean_x=np.mean(all_samples[0,:])
mean_y = np.mean(all_samples[1,:])
mean_z = np.mean(all_samples[2,:])
mean_vector = np.array([[mean_x],[mean_y],[mean_z]])

print('Mean Vector:\n', mean_vector)

Mean Vector:
 [[0.61522918]
 [0.19893197]
 [0.47604385]]


In [20]:
cov_mat = np.cov([all_samples[0,:],all_samples[1,:],all_samples[2,:]])
print('Covariance Matrix:\n', cov_mat)

Covariance Matrix:
 [[1.10475759 0.1738728  0.50140312]
 [0.1738728  0.95020891 0.25554456]
 [0.50140312 0.25554456 1.52774918]]


In [21]:
eig_val_cov, eig_vec_cov = np.linalg.eig(cov_mat)

In [22]:
eig_val_cov


array([1.95546062, 0.77192715, 0.85532791])

In [23]:
eig_vec_cov

array([[ 0.52921002,  0.83878209,  0.12798973],
       [ 0.29387832, -0.03968945, -0.95501847],
       [ 0.79597254, -0.54301875,  0.26750392]])

In [24]:
eig_pairs = [(np.abs(eig_val_cov[i]), eig_vec_cov[:,i]) for i in range(len(eig_val_cov))]
eig_pairs.sort(key=lambda x: x[0], reverse=True)
eig_pairs



[(1.955460618768408, array([0.52921002, 0.29387832, 0.79597254])),
 (0.8553279103392175, array([ 0.12798973, -0.95501847,  0.26750392])),
 (0.7719271543116217, array([ 0.83878209, -0.03968945, -0.54301875]))]

In [25]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(3,1), eig_pairs[1][1].reshape(3,1)))
matrix_w


array([[ 0.52921002,  0.12798973],
       [ 0.29387832, -0.95501847],
       [ 0.79597254,  0.26750392]])

In [27]:
transformed = matrix_w.T.dot(all_samples)
transformed.shape

(2, 40)

The dimension 3 times 40 has been reduced to 2 times 40 by applying above steps similar to PCA.